services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=db_sistema_facturacion
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1011
      ports:
        - "5433:5432"

  backend:
    build:
      #context: .
      dockerfile: Dockerfile
    ports:
      - "9898:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db_sistema_facturacion
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1011
    depends_on:
      - database